export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const STORE_CUSTOMER = 'STORE_CUSTOMER';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
export const UPDATE_CUSTOMER_LIMIT = 'UPDATE_CUSTOMER_LIMIT';
