export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER';
export const STORE_CUSTOMER = 'STORE_CUSTOMER';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
export const UPDATE_CUSTOMER_LIMIT = 'UPDATE_CUSTOMER_LIMIT';
