export const RECEIVE_INVOICES = 'RECEIVE_INVOICES';
export const RECEIVE_INVOICE = 'RECEIVE_INVOICE';
export const STORE_INVOICE = 'STORE_INVOICE';
export const UPDATE_INVOICE_LIMIT = 'UPDATE_INVOICE_LIMIT';
