export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const STORE_INVOICE = 'STORE_INVOICE';
export const CLEAR_INVOICE = 'CLEAR_INVOICE';
export const UPDATE_INVOICE_LIMIT = 'UPDATE_INVOICE_LIMIT';
